### ISSUE TITLE
NOT NULL constraint failed

### ISSUE THREAD

**Issue by wuddel** [samgregory/emuR#1]
I have an EmuDB with 1 session and 136 bundles (created from Praat TextGrids and their according WAV-files) and wanted to `runBASwebservice_all()` on the orthographic transcription level.

While the G2P tokenizer runs, I get:
`Warnung: 'length(x) = 11789 > 1' in coercion to 'logical(1)'Warnung: 'length(x) = 11789 > 1' in coercion to 'logical(1)'`
It runs until 100% is done.

While G2P for pronunciation runs, I get:
`Warnung: 'length(x) = 19564 > 1' in coercion to 'logical(1)'Warnung: 'length(x) = 19564 > 1' in coercion to 'logical(1)'`
It equally runs until 100%

And when MAUS runs, I get: 
`Warnung: 'length(x) = 19564 > 1' in coercion to 'logical(1)'Warnung: 'length(x) = 19564 > 1' in coercion to 'logical(1)'Warnung: 'length(x) = 15850 > 1' in coercion to 'logical(1)'Warnung: 'length(x) = 15850 > 1' in coercion to 'logical(1)'Warnung: 'length(x) = 15850 > 1' in coercion to 'logical(1)'Warnung: 'length(x) = 15850 > 1' in coercion to 'logical(1)'Error: NOT NULL constraint failed: emursegs_tmp.db_uuid`
It stops at 0%.

As a result, the jsons are unchanged.
What does the Error mean? How can I avoid it?

**Comment by wuddel** [comment]
I reduced the database to 4 bundles. 
Calling
```
runBASwebservice_all(
  myDB,
  transcriptionAttributeDefinitionName = "ortho-all",
  language = "deu-DE",
  orthoAttributeDefinitionName = "ORT",
  canoAttributeDefinitionName = "KAN",
  mausAttributeDefinitionName = "MAU",
  minniAttributeDefinitionName = "MINNI",
  sylAttributeDefinitionName = "MAS",
  canoSylAttributeDefinitionName = "KAS",
  chunkAttributeDefinitionName = "TRN",
  runMINNI = TRUE,
  patience = 2,
  resume = TRUE,
  verbose = TRUE
)
```
... causes the same `Error: NOT NULL constraint failed: emursegs_tmp.db_uuid`.
However, if I call the functions separately... G2P-tokenizer first, G2P-for-pronunciation second and MAUS last, I don't get an error. But the function stops at 50% with the message:
```
Warning in for (i in seq_along(snames)) { :to 'logical(1)'Warnung: 'length(x) = 608 > 1' in coercion to 'logical(1)'
  closing unused connection 3 (C:\Users\...\AppData\Local\Temp\Rtmp21cg6s/emuR_bas_workdir/d7ce593f-ce3c-4591-9611-687ea5b005db/maus/....kan.par)
```
The resulting json-files now vontain level ORT with attributes ORT and KAN, and a level MAU.
I can even serve my DB to the EMU webApp.
But when I add Metadata to the database with:
`import_metadata(myDB, "PATH-TO-METADATA/Metadata_short.xlsx")`,
I can't serve the DB anymore. In the Display of the WebApp it says:
`Error validating / checking DBconfig: { "message": "Additional properties not allowed", "code": 303, "dataPath": "/metadataDefaults", "schemaPath": "/additionalProperties", "subErrors": null, "stack": "Error: Additional properties not allowed\n at new d (http://127.0.0.1:17890/dist/emuwebapp.bundle.js:40:117076)\n at i.createError (http://127.0.0.1:17890/dist/emuwebapp.bundle.js:40:98941)\n at i.validateObjectProperties (http://127.0.0.1:17890/dist/emuwebapp.bundle.js:40:110614)\n at i.validateObject (http://127.0.0.1:17890/dist/emuwebapp.bundle.js:40:108957)\n at i.validateAll (http://127.0.0.1:17890/dist/emuwebapp.bundle.js:40:103170)\n at Object.validate (http://127.0.0.1:17890/dist/emuwebapp.bundle.js:40:118211)\n at e.validateJSO (http://127.0.0.1:17890/dist/emuwebapp.bundle.js:181:499835)\n at http://127.0.0.1:17890/dist/emuwebapp.bundle.js:181:341217\n at http://127.0.0.1:17890/dist/emuwebapp.bundle.js:47:95078\n at http://127.0.0.1:17890/dist/emuwebapp.bundle.js:47:95216" }
![Error_in_Serve_DB_after_metadata_import](https://user-images.githubusercontent.com/58472461/187913532-501b5dc3-1613-4e8f-b264-aea10aabed85.png)
`
See also attached image
![Error_in_Serve_DB_after_metadata_import](https://user-images.githubusercontent.com/58472461/187913860-69c2af62-8718-40c0-83e2-4cd31204cdfd.jpg)
